#!/usr/bin/env bash
# Display username, user id, and home directory from /etc/passwd

while IFS=: read -r username password uid gid gecos home shell
do
    echo "$username:$uid:$home"
done < /etc/passwd
