#!/usr/bin/env bash
# This script loops 1 to 10, printing bad luck on 4, good luck on 8, and Best School otherwise
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    counter=$((counter + 1))
done
